import { Equipment } from "../types";

export const GOLD_EQUIPMENTS: Equipment[] = [
  {
    id: "纾难护甲",
    name: "纾难护甲",
    type: "Armor",
    set: "武陵",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 115 },
      { type: "UltRecharge", value: 12.9 },
    ],
  },
  {
    id: "纾难印章",
    name: "纾难印章",
    type: "Accessory",
    set: "武陵",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 43 },
      { type: "UltRecharge", value: 25.7 },
    ],
  },
  {
    id: "纾难印章·壹型",
    name: "纾难印章·壹型",
    type: "Accessory",
    set: "武陵",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 43 },
      { type: "CritRate", value: 10.8 },
    ],
  },
  {
    id: "纾难护手",
    name: "纾难护手",
    type: "Glove",
    set: "武陵",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 86 },
      { type: "UltDmg", value: 45 },
    ],
  },
  {
    id: "纾难重甲",
    name: "纾难重甲",
    type: "Armor",
    set: "武陵",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 115 },
      { type: "NormalDmg", value: 14.4 },
    ],
  },
  {
    id: "纾难识别牌",
    name: "纾难识别牌",
    type: "Accessory",
    set: "武陵",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 43 },
      { type: "DmgReduc", value: 17.8 },
    ],
  },
  {
    id: "纾难识别牌·壹型",
    name: "纾难识别牌·壹型",
    type: "Accessory",
    set: "武陵",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 43 },
      { type: "ComboDmg", value: 43.2 },
    ],
  },
  {
    id: "纾难手套",
    name: "纾难手套",
    type: "Glove",
    set: "武陵",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 86 },
      { type: "AllSkillDmg", value: 24 },
    ],
  },
  {
    id: "拓荒护甲",
    name: "拓荒护甲",
    type: "Armor",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "UltDmg", value: 25.9 },
    ],
  },
  {
    id: "拓荒护甲·壹型",
    name: "拓荒护甲·壹型",
    type: "Armor",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Agility", value: 58 },
      { type: "SkillDmg", value: 20.7 },
    ],
  },
  {
    id: "拓荒护甲·贰型",
    name: "拓荒护甲·贰型",
    type: "Armor",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "SkillDmg", value: 20.7 },
    ],
  },
  {
    id: "拓荒护甲·叁型",
    name: "拓荒护甲·叁型",
    type: "Armor",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "SubStat", value: 10.4 },
    ],
  },
  {
    id: "拓荒护服",
    name: "拓荒护服",
    type: "Armor",
    set: "拓荒",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Agility", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "拓荒耐蚀手套",
    name: "拓荒耐蚀手套",
    type: "Glove",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Intellect", value: 43 },
      { type: "SkillDmg", value: 34.5 },
    ],
  },
  {
    id: "拓荒纤维手套",
    name: "拓荒纤维手套",
    type: "Glove",
    set: "拓荒",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Strength", value: 43 },
      { type: "AllSkillDmg", value: 23 },
    ],
  },
  {
    id: "拓荒通信器",
    name: "拓荒通信器",
    type: "Accessory",
    set: "拓荒",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Agility", value: 21 },
      { type: "ComboDmg", value: 41.4 },
    ],
  },
  {
    id: "拓荒通信器·壹型",
    name: "拓荒通信器·壹型",
    type: "Accessory",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "IceElecDmg", value: 23 },
    ],
  },
  {
    id: "拓荒分析仪",
    name: "拓荒分析仪",
    type: "Accessory",
    set: "拓荒",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 41 },
      { type: "UltDmg", value: 51.7 },
    ],
  },
  {
    id: "拓荒增量供氧栓",
    name: "拓荒增量供氧栓",
    type: "Accessory",
    set: "拓荒",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "SubStat", value: 20.7 },
    ],
  },
  {
    id: "拓荒供氧栓",
    name: "拓荒供氧栓",
    type: "Accessory",
    set: "拓荒",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 41 },
      { type: "PhysDmg", value: 23 },
    ],
  },
  {
    id: "50式应龙重甲",
    name: "50式应龙重甲",
    type: "Armor",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "PhysDmg", value: 11.5 },
    ],
  },
  {
    id: "50式应龙重甲·壹型",
    name: "50式应龙重甲·壹型",
    type: "Armor",
    set: "50式应龙",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "50式应龙重甲·贰型",
    name: "50式应龙重甲·贰型",
    type: "Armor",
    set: "50式应龙",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "ComboDmg", value: 20.7 },
    ],
  },
  {
    id: "50式应龙轻甲",
    name: "50式应龙轻甲",
    type: "Armor",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Strength", value: 58 },
      { type: "AllSkillDmg", value: 13.8 },
    ],
  },
  {
    id: "50式应龙护手",
    name: "50式应龙护手",
    type: "Glove",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Intellect", value: 43 },
      { type: "ComboDmg", value: 34.5 },
    ],
  },
  {
    id: "50式应龙护手·壹型",
    name: "50式应龙护手·壹型",
    type: "Glove",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Agility", value: 43 },
      { type: "ComboDmg", value: 34.5 },
    ],
  },
  {
    id: "50式应龙雷达",
    name: "50式应龙雷达",
    type: "Accessory",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "PhysDmg", value: 23 },
    ],
  },
  {
    id: "50式应龙雷达·壹型",
    name: "50式应龙雷达·壹型",
    type: "Accessory",
    set: "50式应龙",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "UltDmg", value: 51.7 },
    ],
  },
  {
    id: "50式应龙雷达·贰型",
    name: "50式应龙雷达·贰型",
    type: "Accessory",
    set: "50式应龙",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "ComboDmg", value: 41.4 },
    ],
  },
  {
    id: "50式应龙短刃",
    name: "50式应龙短刃",
    type: "Accessory",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Agility", value: 21 },
      { type: "ComboDmg", value: 41.4 },
    ],
  },
  {
    id: "50式应龙短刃·壹型",
    name: "50式应龙短刃·壹型",
    type: "Accessory",
    set: "50式应龙",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Strength", value: 21 },
      { type: "AllSkillDmg", value: 27.6 },
    ],
  },
  {
    id: "M.I.警用护甲",
    name: "M.I.警用护甲",
    type: "Armor",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "ArtsPower", value: 20.7 },
    ],
  },
  {
    id: "M.I.警用罩衣",
    name: "M.I.警用罩衣",
    type: "Armor",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Agility", value: 58 },
      { type: "NormalDmg", value: 13.8 },
    ],
  },
  {
    id: "M.I.警用罩衣·壹型",
    name: "M.I.警用罩衣·壹型",
    type: "Armor",
    set: "M.I.警用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "CritRate", value: 5.2 },
    ],
  },
  {
    id: "M.I.警用罩衣·贰型",
    name: "M.I.警用罩衣·贰型",
    type: "Armor",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Agility", value: 58 },
      { type: "SkillDmg", value: 20.7 },
    ],
  },
  {
    id: "M.I.警用手套",
    name: "M.I.警用手套",
    type: "Glove",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Strength", value: 43 },
      { type: "SkillDmg", value: 34.5 },
    ],
  },
  {
    id: "M.I.警用手环",
    name: "M.I.警用手环",
    type: "Glove",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Agility", value: 43 },
      { type: "NormalDmg", value: 23 },
    ],
  },
  {
    id: "M.I.警用手环·壹型",
    name: "M.I.警用手环·壹型",
    type: "Glove",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "CritRate", value: 8.6 },
    ],
  },
  {
    id: "M.I.警用臂环",
    name: "M.I.警用臂环",
    type: "Accessory",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "IceElecDmg", value: 23 },
    ],
  },
  {
    id: "M.I.警用瞄具",
    name: "M.I.警用瞄具",
    type: "Accessory",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "M.I.警用工具组",
    name: "M.I.警用工具组",
    type: "Accessory",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Agility", value: 21 },
      { type: "CritRate", value: 10.4 },
    ],
  },
  {
    id: "M.I.警用刺刃",
    name: "M.I.警用刺刃",
    type: "Accessory",
    set: "M.I.警用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "FireNatDmg", value: 23 },
    ],
  },
  {
    id: "M.I.警用刺刃·壹型",
    name: "M.I.警用刺刃·壹型",
    type: "Accessory",
    set: "M.I.警用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Agility", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "M.I.警用护甲·壹型",
    name: "M.I.警用护甲·壹型",
    type: "Armor",
    set: "M.I.警用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "M.I.警用手套·壹型",
    name: "M.I.警用手套·壹型",
    type: "Glove",
    set: "M.I.警用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Intellect", value: 43 },
      { type: "UltDmg", value: 43.1 },
    ],
  },
  {
    id: "M.I.警用瞄具·壹型",
    name: "M.I.警用瞄具·壹型",
    type: "Accessory",
    set: "M.I.警用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "CritRate", value: 10.4 },
    ],
  },
  {
    id: "碾骨重护甲",
    name: "碾骨重护甲",
    type: "Armor",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "碾骨重护甲·壹型",
    name: "碾骨重护甲·壹型",
    type: "Armor",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "ComboDmg", value: 20.7 },
    ],
  },
  {
    id: "碾骨披巾",
    name: "碾骨披巾",
    type: "Armor",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Strength", value: 58 },
      { type: "ComboDmg", value: 20.7 },
    ],
  },
  {
    id: "碾骨披巾·壹型",
    name: "碾骨披巾·壹型",
    type: "Armor",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Agility", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "碾骨腕带",
    name: "碾骨腕带",
    type: "Glove",
    set: "碾骨",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 65 },
      { type: "Agility", value: 43 },
      { type: "FireNatDmg", value: 19.2 },
    ],
  },
  {
    id: "碾骨腕带·壹型",
    name: "碾骨腕带·壹型",
    type: "Glove",
    set: "碾骨",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Strength", value: 43 },
      { type: "IceElecDmg", value: 19.2 },
    ],
  },
  {
    id: "碾骨小雕像",
    name: "碾骨小雕像",
    type: "Accessory",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Agility", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "碾骨面具",
    name: "碾骨面具",
    type: "Accessory",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "BreakDmg", value: 41.4 },
    ],
  },
  {
    id: "碾骨面具·壹型",
    name: "碾骨面具·壹型",
    type: "Accessory",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "CritRate", value: 10.4 },
    ],
  },
  {
    id: "碾骨小雕像·壹型",
    name: "碾骨小雕像·壹型",
    type: "Accessory",
    set: "碾骨",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "ComboDmg", value: 41.4 },
    ],
  },
  {
    id: "碾骨面具·贰型",
    name: "碾骨面具·贰型",
    type: "Accessory",
    set: "碾骨",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "碾骨重护甲·贰型",
    name: "碾骨重护甲·贰型",
    type: "Armor",
    set: "碾骨",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "IceElecDmg", value: 11.5 },
    ],
  },
  {
    id: "落潮轻甲",
    name: "落潮轻甲",
    type: "Armor",
    set: "潮涌",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Strength", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "潮涌手甲",
    name: "潮涌手甲",
    type: "Glove",
    set: "潮涌",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "IceElecDmg", value: 19.2 },
    ],
  },
  {
    id: "悬河供氧栓",
    name: "悬河供氧栓",
    type: "Accessory",
    set: "潮涌",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "IceElecDmg", value: 23 },
    ],
  },
  {
    id: "浊流切割炬",
    name: "浊流切割炬",
    type: "Accessory",
    set: "潮涌",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Strength", value: 21 },
      { type: "NormalDmg", value: 27.6 },
    ],
  },
  {
    id: "脉冲式干扰服",
    name: "脉冲式干扰服",
    type: "Armor",
    set: "脉冲式",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "ArtsPower", value: 20.7 },
    ],
  },
  {
    id: "脉冲式手套",
    name: "脉冲式手套",
    type: "Glove",
    set: "脉冲式",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Intellect", value: 43 },
      { type: "IceElecDmg", value: 19.2 },
    ],
  },
  {
    id: "脉冲式探针",
    name: "脉冲式探针",
    type: "Accessory",
    set: "脉冲式",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Agility", value: 21 },
      { type: "ArtsPower", value: 41.4 },
    ],
  },
  {
    id: "脉冲式校准器",
    name: "脉冲式校准器",
    type: "Accessory",
    set: "脉冲式",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 41 },
      { type: "ArtsPower", value: 41.4 },
    ],
  },
  {
    id: "脉冲式侵入核",
    name: "脉冲式侵入核",
    type: "Accessory",
    set: "脉冲式",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 41 },
      { type: "UltDmg", value: 51.7 },
    ],
  },
  {
    id: "动火用外骨骼",
    name: "动火用外骨骼",
    type: "Armor",
    set: "动火用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Agility", value: 58 },
      { type: "FireNatDmg", value: 11.5 },
    ],
  },
  {
    id: "动火用辅助骨骼",
    name: "动火用辅助骨骼",
    type: "Armor",
    set: "动火用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "FireNatDmg", value: 11.5 },
    ],
  },
  {
    id: "动火用手套",
    name: "动火用手套",
    type: "Glove",
    set: "动火用",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "ArtsPower", value: 34.5 },
    ],
  },
  {
    id: "动火用手甲",
    name: "动火用手甲",
    type: "Glove",
    set: "动火用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Strength", value: 43 },
      { type: "FireNatDmg", value: 19.2 },
    ],
  },
  {
    id: "动火用手甲·壹型",
    name: "动火用手甲·壹型",
    type: "Glove",
    set: "动火用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Intellect", value: 43 },
      { type: "FireNatDmg", value: 19.2 },
    ],
  },
  {
    id: "动火用储能匣",
    name: "动火用储能匣",
    type: "Accessory",
    set: "动火用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Agility", value: 21 },
      { type: "ArtsPower", value: 41.4 },
    ],
  },
  {
    id: "动火用测温镜",
    name: "动火用测温镜",
    type: "Accessory",
    set: "动火用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 41 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "动火用电力匣",
    name: "动火用电力匣",
    type: "Accessory",
    set: "动火用",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "ArtsPower", value: 41.4 },
    ],
  },
  {
    id: "生物辅助重甲",
    name: "生物辅助重甲",
    type: "Armor",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "HealEffect", value: 10.4 },
    ],
  },
  {
    id: "生物辅助胸甲",
    name: "生物辅助胸甲",
    type: "Armor",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "HealEffect", value: 10.4 },
    ],
  },
  {
    id: "生物辅助臂甲",
    name: "生物辅助臂甲",
    type: "Glove",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "UltRecharge", value: 20.5 },
    ],
  },
  {
    id: "生物辅助手甲",
    name: "生物辅助手甲",
    type: "Glove",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Strength", value: 43 },
      { type: "HealEffect", value: 17.3 },
    ],
  },
  {
    id: "生物辅助接驳器",
    name: "生物辅助接驳器",
    type: "Accessory",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "DmgReduc", value: 17.1 },
    ],
  },
  {
    id: "生物辅助接驳器·贰型",
    name: "生物辅助接驳器·贰型",
    type: "Accessory",
    set: "生物辅助",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 41 },
      { type: "HP", value: 41.4 },
    ],
  },
  {
    id: "生物辅助护板",
    name: "生物辅助护板",
    type: "Accessory",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "MainStat", value: 20.7 },
    ],
  },
  {
    id: "生物辅助护盾针",
    name: "生物辅助护盾针",
    type: "Accessory",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 41 },
      { type: "HealEffect", value: 20.7 },
    ],
  },
  {
    id: "生物辅助接驳器·壹型",
    name: "生物辅助接驳器·壹型",
    type: "Accessory",
    set: "生物辅助",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "HP", value: 41.4 },
    ],
  },
  {
    id: "点剑轻装甲",
    name: "点剑轻装甲",
    type: "Armor",
    set: "点剑",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "点剑重装甲",
    name: "点剑重装甲",
    type: "Armor",
    set: "点剑",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "ArtsPower", value: 20.7 },
    ],
  },
  {
    id: "点剑战术手套",
    name: "点剑战术手套",
    type: "Glove",
    set: "点剑",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "PhysDmg", value: 19.2 },
    ],
  },
  {
    id: "点剑战术手甲",
    name: "点剑战术手甲",
    type: "Glove",
    set: "点剑",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Strength", value: 43 },
      { type: "UltDmg", value: 43.1 },
    ],
  },
  {
    id: "点剑定位信标",
    name: "点剑定位信标",
    type: "Accessory",
    set: "点剑",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 41 },
      { type: "ArtsPower", value: 41.4 },
    ],
  },
  {
    id: "点剑微型滤芯",
    name: "点剑微型滤芯",
    type: "Accessory",
    set: "点剑",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "PhysDmg", value: 23 },
    ],
  },
  {
    id: "点剑火石",
    name: "点剑火石",
    type: "Accessory",
    set: "点剑",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "PhysDmg", value: 23 },
    ],
  },
  {
    id: "长息装甲",
    name: "长息装甲",
    type: "Armor",
    set: "长息",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "ArtsPower", value: 20.7 },
    ],
  },
  {
    id: "长息护手",
    name: "长息护手",
    type: "Glove",
    set: "长息",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Strength", value: 43 },
      { type: "UltRecharge", value: 20.5 },
    ],
  },
  {
    id: "长息护手·壹型",
    name: "长息护手·壹型",
    type: "Glove",
    set: "长息",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "UltRecharge", value: 20.5 },
    ],
  },
  {
    id: "长息蓄电核",
    name: "长息蓄电核",
    type: "Accessory",
    set: "长息",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Strength", value: 21 },
      { type: "UltRecharge", value: 24.6 },
    ],
  },
  {
    id: "长息蓄电核·壹型",
    name: "长息蓄电核·壹型",
    type: "Accessory",
    set: "长息",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "HealEffect", value: 20.7 },
    ],
  },
  {
    id: "长息辅助臂",
    name: "长息辅助臂",
    type: "Accessory",
    set: "长息",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "UltRecharge", value: 24.6 },
    ],
  },
  {
    id: "轻超域护板",
    name: "轻超域护板",
    type: "Armor",
    set: "轻超域",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Strength", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "BreakDmg", value: 20.7 },
    ],
  },
  {
    id: "轻超域护手",
    name: "轻超域护手",
    type: "Glove",
    set: "轻超域",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Strength", value: 43 },
      { type: "ArtsPower", value: 34.5 },
    ],
  },
  {
    id: "轻超域轻护手",
    name: "轻超域轻护手",
    type: "Glove",
    set: "轻超域",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Agility", value: 43 },
      { type: "AllSkillDmg", value: 23 },
    ],
  },
  {
    id: "轻超域分析环",
    name: "轻超域分析环",
    type: "Accessory",
    set: "轻超域",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "PhysDmg", value: 23 },
    ],
  },
  {
    id: "轻超域稳定盘",
    name: "轻超域稳定盘",
    type: "Accessory",
    set: "轻超域",
    dispatchCost: 8000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "ArtsPower", value: 41.4 },
    ],
  },
  {
    id: "轻超域稳定盘·壹型",
    name: "轻超域稳定盘·壹型",
    type: "Accessory",
    set: "轻超域",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "PhysDmg", value: 23 },
    ],
  },
  {
    id: "轻超域腕表",
    name: "轻超域腕表",
    type: "Accessory",
    set: "轻超域",
    dispatchCost: 16000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Agility", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "清波重甲",
    name: "清波重甲",
    type: "Armor",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "UltRecharge", value: 12.3 },
    ],
  },
  {
    id: "清波轻甲",
    name: "清波轻甲",
    type: "Armor",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Intellect", value: 87 },
      { type: "Willpower", value: 58 },
      { type: "ArtsPower", value: 20 },
    ],
  },
  {
    id: "清波手甲",
    name: "清波手甲",
    type: "Glove",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Agility", value: 65 },
      { type: "Strength", value: 43 },
      { type: "AllSkillDmg", value: 23 },
    ],
  },
  {
    id: "清波护手",
    name: "清波护手",
    type: "Glove",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "UltRecharge", value: 20.5 },
    ],
  },
  {
    id: "清波定位仪",
    name: "清波定位仪",
    type: "Accessory",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "清波竹刃",
    name: "清波竹刃",
    type: "Accessory",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Strength", value: 32 },
      { type: "Agility", value: 21 },
      { type: "FireNatDmg", value: 23 },
    ],
  },
  {
    id: "清波水罐",
    name: "清波水罐",
    type: "Accessory",
    set: "清波",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Willpower", value: 21 },
      { type: "ArtsPower", value: 41 },
    ],
  },
  {
    id: "壤流轻甲",
    name: "壤流轻甲",
    type: "Armor",
    set: "壤流",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Willpower", value: 87 },
      { type: "Intellect", value: 58 },
      { type: "IceElecDmg", value: 11.5 },
    ],
  },
  {
    id: "壤流护手",
    name: "壤流护手",
    type: "Glove",
    set: "壤流",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Intellect", value: 43 },
      { type: "IceElecDmg", value: 19.2 },
    ],
  },
  {
    id: "壤流短棍",
    name: "壤流短棍",
    type: "Accessory",
    set: "壤流",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "拓荒纤维手套·壹型",
    name: "拓荒纤维手套·壹型",
    type: "Glove",
    set: "拓荒",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Intellect", value: 65 },
      { type: "Agility", value: 43 },
      { type: "UltRecharge", value: 20.5 },
    ],
  },
  {
    id: "拓荒增量供氧栓·壹型",
    name: "拓荒增量供氧栓·壹型",
    type: "Accessory",
    set: "拓荒",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Intellect", value: 32 },
      { type: "Agility", value: 21 },
      { type: "SubStat", value: 20.7 },
    ],
  },
  {
    id: "碾骨手套",
    name: "碾骨手套",
    type: "Glove",
    set: "碾骨",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Willpower", value: 65 },
      { type: "Agility", value: 43 },
      { type: "IceElecDmg", value: 19.2 },
    ],
  },
  {
    id: "碾骨小雕像·贰型",
    name: "碾骨小雕像·贰型",
    type: "Accessory",
    set: "碾骨",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Willpower", value: 32 },
      { type: "Intellect", value: 21 },
      { type: "SkillDmg", value: 41.4 },
    ],
  },
  {
    id: "点剑重装甲·壹型",
    name: "点剑重装甲·壹型",
    type: "Armor",
    set: "点剑",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 56 },
    subStats: [
      { type: "Agility", value: 87 },
      { type: "Strength", value: 58 },
      { type: "PhysDmg", value: 11.5 },
    ],
  },
  {
    id: "点剑战术手甲·壹型",
    name: "点剑战术手甲·壹型",
    type: "Glove",
    set: "点剑",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 42 },
    subStats: [
      { type: "Strength", value: 65 },
      { type: "Willpower", value: 43 },
      { type: "ArtsPower", value: 34 },
    ],
  },
  {
    id: "点剑短刃",
    name: "点剑短刃",
    type: "Accessory",
    set: "点剑",
    dispatchCost: 25000,
    mainStat: { type: "Defense", value: 21 },
    subStats: [
      { type: "Agility", value: 32 },
      { type: "Strength", value: 21 },
      { type: "UltDmg", value: 51.8 },
    ],
  },
];
